#!/bin/sh
########################################################################
#
# Description : risd
#
# Authors     : John K. <jklimek@email.com>
# Version     : 1.0
# Notes       : https://github.com/sofakng/risd
#
########################################################################

RISD_BINARY=/media/fat/linux/risd
RISD_CONSOLE_LOG=0			# 0 = disabled,    1 = console logging

[ -f $RISD_BINARY ] || exit 0

is_running() {
	[ ! -z "$(pidof risd)" ]
}

status() {
	if is_running ; then
                echo "risd server is running."
	else
                echo "risd server is NOT running."
        fi
}

start() {
	if is_running ; then
		echo "risd service is already running."
		exit 0
	fi

	printf "Starting risd service: "

	if [ "$RISD_CONSOLE_LOG" = "1" ]; then
		$RISD_BINARY &
	else
		$RISD_BINARY >/dev/null 2>&1 &
	fi

	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        if ! is_running ; then
                echo "risd service is not running."
                exit 0
        fi

	printf "Shutting down risd service: "
	kill -9 `pidof risd`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  status)
        status
        ;;
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit $?
